=== consultant-1379/ERICPmPatternEmulator/ERICpmpatternemulator_CXP9036399/Controller/src/main/resources/config/xsd/param_config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ParamConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PatternLocation" type="xs:string" />
        <xs:element name="OutputLocation" type="xs:string" />
        <xs:element name="Analysis">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="EventToAnalyze">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="ParamToAnalyze">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="ListValue" type="xs:string" />
                          <xs:element minOccurs="0" name="MinValue" type="xs:long" />
                          <xs:element minOccurs="0" name="MaxValue" type="xs:long" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="isRequired" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="Enrichment">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="EventToEnrich">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ParamToEnrich">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="ListValue" type="xs:string" />
                          <xs:element minOccurs="0" name="MinValue" type="xs:long" />
                          <xs:element minOccurs="0" name="MaxValue" type="xs:long" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="isRequired" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventAddition">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="EventToAdd">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="referenceEvent" type="xs:string" use="required" />
                  <xs:attribute name="position" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="isRequired" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== consultant-1379/ERICPmPatternEmulator/ERICpmpatternemulator_CXP9036399/Controller/src/main/resources/config/param_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<ParamConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/param_config.xsd">
  <PatternLocation>K:\TEST_DATA\NewTool\output</PatternLocation>
  <OutputLocation>K:\TEST_DATA\NewTool\out</OutputLocation>
  <Analysis isRequired="NO">
	  <EventToAnalyze name="INTERNAL_EVENT_ERAB_DATA_INFO">
	   <ParamToAnalyze name="EVENT_PARAM_GLOBAL_CELL_ID:2" type="MinMax">
	    	<MinValue>25</MinValue>
	    	<MaxValue>28</MaxValue>
	    </ParamToAnalyze>
	    <ParamToAnalyze name="EVENT_PARAM_MMES1APID" type="All"></ParamToAnalyze>
	  </EventToAnalyze>
	  <EventToAnalyze name="INTERNAL_PROC_RRC_CONN_RECONF_NO_MOB">
	    <ParamToAnalyze name="EVENT_PARAM_MMES1APID" type="List">
	    	<ListValue>68662681</ListValue>
	    	<ListValue>467366820</ListValue>
	    </ParamToAnalyze>
	  </EventToAnalyze>
  </Analysis>
  <Enrichment isRequired="NO">
	  <EventToEnrich name="INTERNAL_EVENT_ERAB_DATA_INFO">
	   <ParamToEnrich name="EVENT_PARAM_GLOBAL_CELL_ID:2" type="MinMax">
	    	<MinValue>25</MinValue>
	    	<MaxValue>28</MaxValue>
	    </ParamToEnrich>
	  </EventToEnrich>
	  <EventToEnrich name="INTERNAL_PROC_RRC_CONN_RECONF_NO_MOB">
	    <ParamToEnrich name="EVENT_PARAM_MMES1APID" type="List">
	    	<ListValue>68662681</ListValue>
	    	<ListValue>467366820</ListValue>
	    </ParamToEnrich>
	  </EventToEnrich>
  </Enrichment>
  <EventAddition isRequired="YES">
  	<EventToAdd name="INTERNAL_EVENT_ERAB_DATA_INFO" referenceEvent="INTERNAL_PROC_RRC_CONN_RECONF_NO_MOB" position="BEFORE"></EventToAdd>
  	<EventToAdd name="INTERNAL_EVENT_ERAB_DATA_INFO" referenceEvent="INTERNAL_PROC_RRC_CONN_RECONF_NO_MOB" position="AFTER"></EventToAdd>
  </EventAddition>
</ParamConfig>
